export const GETCONTACT_SUCCESS = "GETCONTACT_SUCCESS";
export const GETCONTACT_FAIL = "GETCONTACT_FAIL";

export const POSTCONTACT_SUCCESS = "POSTCONTACT_SUCCESS";
export const POSTCONTACT_FAIL = "POSTCONTACT_FAIL";

export const PUTCONTACT_SUCCESS = "PUTCONTACT_SUCCESS";
export const PUTCONTACT_FAIL = "PUTCONTACT_FAIL";

export const DELETECONTACT_SUCCESS = "DELETECONTACT_SUCCESS";
export const DELETECONTACT_FAIL = "DELETECONTACT_FAIL";